name: Lint and Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - uses: ./.github/actions/go
        with:
          cache-dependency-path: |
            cosmo-router/plugins/users/go.sum
          go-version: 1.24
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "29.3"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/go-setup-tools
      - name: Generate code
        working-directory: ./cosmo-router/plugins/users
        run: npm run generate

      - uses: ./.github/actions/go-mod-tidy
        with:
          working-directory: ./cosmo-router/plugins/users/


      - name: Lint
        uses: ./.github/actions/go-linter
        with:
          working-directory: ./cosmo-router/plugins/users/

      - name: Test
        working-directory: ./cosmo-router/plugins/users/
        run: |
          gotestsum -f github-actions -- -race ./...
        
        
        
          